In [4]:
import numpy as np

## Numpy arrays

In [5]:
benimlistem = [20,30,40]

In [6]:
np.array(benimlistem)

array([20, 30, 40])

In [8]:
matrixlistesi = [[10,20,30],[20,30,40],[30,40,50]]

In [10]:
np.array(matrixlistesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange


In [11]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((2,2))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [29]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

## eye

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [36]:
np.random.randn(4)

array([ 0.10381706,  0.24824551, -0.76786433, -0.84777266])

In [37]:
np.random.randn(2,2)

array([[ 0.15452006,  0.54145209],
       [ 0.44500615, -1.55810192]])

In [52]:
np.random.randint(1,10)

8

In [55]:
np.random.randint(1,300,5)##1 dahil 300 dahil değil 5 sayı seç

array([227, 139,  35, 252,  89])

In [56]:
benimNumpyDizim = np.arange(30)

In [57]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## numpy dizi methodları

In [60]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [61]:
benimRandomDizim = np.random.randint(1,100,20)

In [62]:
benimRandomDizim

array([36, 75,  3, 83,  7, 10, 82, 17, 95, 20, 58, 78, 80, 17, 22, 55, 32,
       28, 57, 74])

In [64]:
benimRandomDizim.max()

95

In [65]:
benimRandomDizim.min()

3

In [66]:
benimRandomDizim.argmax()

8

In [67]:
benimRandomDizim.argmin()

2

In [68]:
benimNumpyDizim.shape

(30,)