In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[5]

5

In [7]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [8]:
benimDizim[3:8] = -5

In [9]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [19]:
baskaDizi = np.arange(0,24)

In [20]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
slicingDizisi = baskaDizi[4:9]

In [22]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [23]:
slicingDizisi [:] = 700

In [24]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [25]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [26]:
ornekDizi = np.arange(0,24) ## değiştirmemek için ise şöyle yapmak gerekiyor

In [27]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [28]:
ornekDiziKopyasi = ornekDizi.copy()

In [29]:
OrnekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [31]:
OrnekDiziKopyaSlicing

array([3, 4, 5])

In [32]:
OrnekDiziKopyaSlicing[:] = 800

In [33]:
OrnekDiziKopyaSlicing

array([800, 800, 800])

In [35]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [36]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [37]:
benimMatrixDizim = np.array(benimListem)

In [38]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [39]:
benimMatrixDizim[0]

array([10, 20, 30])

In [40]:
benimMatrixDizim[1][2]

40

In [42]:
benimMatrixDizim[1,2]## aynı şey

40

In [44]:
benimMatrixDizim[1:,2:]

array([[40],
       [60]])

In [45]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]

In [46]:
yeniMatrix = np.array(yeniListe)

In [47]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [51]:
yeniMatrix[[0,1,0]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

## operasyonlar

In [56]:
yeniBirDizi = np.random.randint(1,100,20)

In [57]:
yeniBirDizi

array([54, 25, 34, 64, 84, 32, 12, 57, 21,  7, 24, 43, 62, 30, 49, 45, 44,
       16, 11, 60])

In [60]:
yeniBirDizi > 50  

array([ True, False, False,  True,  True, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True])

In [64]:
for rakam in yeniBirDizi:
    if rakam > 50:
        print(rakam)
        continue

54
64
84
57
62
60


In [65]:
sonucDizisi = yeniBirDizi > 50

In [66]:
sonucDizisi

array([ True, False, False,  True,  True, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True])

In [67]:
yeniBirDizi

array([54, 25, 34, 64, 84, 32, 12, 57, 21,  7, 24, 43, 62, 30, 49, 45, 44,
       16, 11, 60])

In [68]:
yeniBirDizi[sonucDizisi]

array([54, 64, 84, 57, 62, 60])

In [70]:
sonDizi = np.arange(0,24)

In [71]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [72]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [73]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [74]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [77]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])